# Generated by Django 4.0.2 on 2022-02-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0003_rename_carro_id_contato_car_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='carro_url',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
