# Generated by Django 4.0.2 on 2022-02-14 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_teams_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='ultimo_nome',
            new_name='sobrenome',
        ),
    ]
