# Generated by Django 4.0.2 on 2022-02-14 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_ultimo_nome_team_sobrenome'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Equipe',
        ),
    ]
