# Generated by Django 4.0.2 on 2022-02-14 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carro_nome', models.CharField(max_length=255)),
                ('carro_url', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=100)),
                ('cidade', models.CharField(max_length=150)),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], verbose_name='ano')),
                ('carroceria', models.CharField(max_length=100)),
                ('motor', models.CharField(max_length=100)),
                ('transmissao', models.CharField(max_length=100)),
                ('recursos', models.CharField(choices=[('Cruise Control', 'Cruise Control'), ('Audio Interface', 'Audio Interface'), ('Airbags', 'Airbags'), ('Air Conditioning', 'Air Conditioning'), ('Seat Heating', 'Seat Heating'), ('Alarm System', 'Alarm System'), ('ParkAssist', 'ParkAssist'), ('Power Steering', 'Power Steering'), ('Reversing Camera', 'Reversing Camera'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Wind Deflector', 'Wind Deflector'), ('Bluetooth Handset', 'Bluetooth Handset')], max_length=100)),
                ('interior', models.CharField(max_length=100)),
                ('km', models.IntegerField()),
                ('combustivel', models.CharField(max_length=100)),
                ('is_featured', models.BooleanField(max_length=100)),
                ('descricao', models.TextField(max_length=900)),
                ('car_photo', models.ImageField(upload_to='fotos/%Y/%m/%d/')),
                ('car_photo_1', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/')),
                ('car_photo_2', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/')),
                ('car_photo_3', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/')),
                ('car_photo_4', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/')),
                ('car_photo_5', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/')),
                ('car_photo_6', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/')),
                ('car_photo_7', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/')),
                ('car_photo_8', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/')),
                ('data_add', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
