# Generated by Django 4.0.2 on 2022-02-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='carro_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
