# Generated by Django 4.0.2 on 2022-02-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0004_carro_outros_recursos_alter_carro_ano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='car_photo_1',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/ '),
        ),
    ]
