# Generated by Django 4.0.2 on 2022-02-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0005_alter_carro_car_photo_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='preco',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carro',
            name='preco_promo',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carro',
            name='car_photo_1',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
