# Generated by Django 4.0.2 on 2022-02-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0006_carro_preco_carro_preco_promo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='seo_alt',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carro',
            name='seo_meta',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carro',
            name='preco',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='carro',
            name='preco_promo',
            field=models.FloatField(blank=True),
        ),
    ]
