# Generated by Django 4.0.2 on 2022-02-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0007_carro_seo_alt_carro_seo_meta_alter_carro_preco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='preco',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='carro',
            name='preco_promo',
            field=models.IntegerField(blank=True),
        ),
    ]
