# Generated by Django 4.0.2 on 2022-02-15 16:11

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0008_alter_carro_preco_alter_carro_preco_promo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carro',
            old_name='transmissao',
            new_name='marca',
        ),
        migrations.AlterField(
            model_name='carro',
            name='recursos',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Controle de Tração', 'Controle de Tração'), ('Sensor de Estacionamento', 'Sensor de Estacionamento'), ('Airbags', 'Airbags'), ('Ar Condicionado', 'Ar Condicionado'), ('Bancos com Aquecimento', 'Bancos com Aquecimento'), ('Difusor de Escapamento', 'Difusor de Escapamento'), ('ParkAssist', 'ParkAssist'), ('Camera de Ré', 'Camera de Ré'), ('Sensor de Estacionamento Traseiro', 'Sensor de Estacionamento Traseiro'), ('Sensor de Estacionamento Dianteiro', 'Sensor de Estacionamento Dianteiro'), ('Start/Stop', 'Start/Stop'), ('Sensor de Colisão', 'Sensor de Colisão'), ('Bluetooth Handset', 'Bluetooth Handset')], max_length=253),
        ),
    ]
