# Generated by Django 4.0.2 on 2022-02-15 16:12

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0009_rename_transmissao_carro_marca_alter_carro_recursos'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='transmissao',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Automática', 'Automática'), ('Manual', 'Manual')], default=1, max_length=17),
            preserve_default=False,
        ),
    ]
